spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easy_account
    username: root
    password: srj12356
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8181

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.shirj.api.entity
  config-location: classpath:mybatis-config.xml
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.shirj.api.entity
#  config-location: classpath:mybatis-config.xml

##log##
logging:
  config: classpath:logback.xml
  level:
    com.shirj.api.dao: debug
    com.shirj.api.service: debug
    com.shirj.svc.service: debug