DELIMITER //
CREATE PROCEDURE addAccountType()
BEGIN
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2)
    VALUES ('ACCOUNT_TYPE', 0, 'CASH', '现金账户');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2)
    VALUES ('ACCOUNT_TYPE', 1, 'CREDIT', '信用账户');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2)
    VALUES ('ACCOUNT_TYPE', 2, 'RECHARGE', '充值账户');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2)
    VALUES ('ACCOUNT_TYPE', 3, 'INVEST', '投资账户');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2)
    VALUES ('ACCOUNT_TYPE', 4, 'DEBT', '债务');

    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CASH', 0, 'DEBIT_CARD', '储蓄卡');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CASH', 1, 'WECHAT_WALLET', '微信钱包');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CASH', 2, 'ALIPAY', '支付宝');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CASH', 3, 'CASH_WALLET', '现金钱包');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CASH', 4, 'YUE_BAO', '余额宝');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CASH', 5, 'WECHAT_CHANGE', '微信零钱通');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CASH', 6, 'OTHER', '其他');

    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CREDIT', 10, 'CREDIT_CARD', '信用卡');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CREDIT', 11, 'ANT_FLOWER', '蚂蚁花呗');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CREDIT', 12, 'JINGDONG_WHITE', '京东白条');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CREDIT', 13, 'INSTALLMENT_LOAN', '分期贷款');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('CREDIT', 14, 'OTHER', '其他');

    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('RECHARGE', 20, 'BUS_CARD', '公交卡');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('RECHARGE', 21, 'SCHOOL_CARD', '校园卡');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('RECHARGE', 22, 'PROVIDENT_FUND', '公积金');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('RECHARGE', 23, 'OTHER', '其他');

    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('INVEST', 30, 'STOCK', '股票');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('INVEST', 31, 'FUND', '基金');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('INVEST', 32, 'DIGITAL_CURRENCY', '数字货币');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('INVEST', 33, 'INVEST', '其他');

    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('DEBT', 40, 'BORROW', '借入');
    INSERT INTO t_param (TYPE_ID, DATA_ID, SUB_PARAM1, SUB_PARAM2) VALUES ('DEBT', 41, 'LEND', '借出');
END//
DELIMITER ;
CALL addAccountType();
DROP PROCEDURE addAccountType;